-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "quantity" DROP NOT NULL,
ALTER COLUMN "quantity" SET DATA TYPE TEXT,
ALTER COLUMN "totalReviews" DROP NOT NULL,
ALTER COLUMN "totalReviews" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "ProductReview" ALTER COLUMN "rate" DROP NOT NULL,
ALTER COLUMN "rate" SET DATA TYPE TEXT;
